@startuml
title
企業商品管理者が可能な操作
end title

:企業管理者: as item_administrator
(商品の登録) as item
(商品一覧で表示される) as item_list
(商品情報の変更\n（個数変更含む）) as item_change_information
(商品の削除) as delete_item
(アカウント情報閲覧) as account_info
(アカウント情報の変更) as change_account_info
(アカウントのパスワードの変更) as change_password
(アカウントのユーザ名の変更) as change_user_name

item_administrator --> item
item --> item_list : 反映

item_administrator --> delete_item
delete_item --> item_list : 反映

item_administrator --> item_change_information
item_change_information --> item_list : 反映

top to bottom direction
item_administrator ----> account_info
account_info -> change_account_info
change_account_info -> change_user_name
change_account_info --> change_password

@enduml